# Generated by Django 4.2.23 on 2025-07-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default='aaaa', editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
